version: "3"

services:
  consul:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    volumes:
     - ./conf/server.json:/consul/config/server.json:ro
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    command: "agent"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
  app:
    build: .
    container_name: application
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - consul